  [[main]]
  name = "About Me"
  identifier = "aboutme"
  weight = 100
  url = "/about/"

  [[main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

[[main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/" 
